# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
  
[[main]]
  name = "Research"
  url = "#research-home"
  weight = 10
  
[[main]]
  name = "Teaching"
  url = "#mentorship"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40
  
[[main]]
  name = "Shiny"
  url = "https://ameliaritger.shinyapps.io/mbon-shiny-app/"
  weight = 50

[[main]]
  name = "About"
  url = "#about"
  weight = 60

[[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 70
