---
title: Assignment 1 - Task 2
author: ''
date: '2020-02-28'
slug: udsa-nutrients
categories: []
tags:
  - dogs
  - hiking
subtitle: ''
summary: ''
authors: []
lastmod: '2020-01-09T15:02:28-08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>The following is an exploration of food nutrient information provided by the <a href="https://fdc.nal.usda.gov/index.html">USDA National Nutrient Database</a>. Specifically, I examine variation in nutrients (such as fat, vitamin E, and iron) present in baby food using a principal components analysis (PCA). Using a PCA will allow me to explore the multi-dimensionality of many nutrients (23, to be specific) present in baby food in a format that my adult brain can better comprehend.</p>
<div id="so-lets-get-started" class="section level4">
<h4>So, let’s get started!</h4>
<pre class="r"><code>#load the packages
library(tidyverse)
library(janitor)
library(naniar)
library(VIM)
library(skimr)
library(ggfortify)

#Input the data
food &lt;- read_csv(&quot;usda_nutrients.csv&quot;)

#Take a look at the data
unique(food$FoodGroup)</code></pre>
<pre><code>##  [1] &quot;Dairy and Egg Products&quot;              &quot;Spices and Herbs&quot;                   
##  [3] &quot;Baby Foods&quot;                          &quot;Fats and Oils&quot;                      
##  [5] &quot;Poultry Products&quot;                    &quot;Soups, Sauces, and Gravies&quot;         
##  [7] &quot;Sausages and Luncheon Meats&quot;         &quot;Breakfast Cereals&quot;                  
##  [9] &quot;Snacks&quot;                              &quot;Fruits and Fruit Juices&quot;            
## [11] &quot;Pork Products&quot;                       &quot;Vegetables and Vegetable Products&quot;  
## [13] &quot;Nut and Seed Products&quot;               &quot;Beef Products&quot;                      
## [15] &quot;Beverages&quot;                           &quot;Finfish and Shellfish Products&quot;     
## [17] &quot;Legumes and Legume Products&quot;         &quot;Lamb, Veal, and Game Products&quot;      
## [19] &quot;Baked Products&quot;                      &quot;Sweets&quot;                             
## [21] &quot;Cereal Grains and Pasta&quot;             &quot;Fast Foods&quot;                         
## [23] &quot;Meals, Entrees, and Side Dishes&quot;     &quot;American Indian/Alaska Native Foods&quot;
## [25] &quot;Restaurant Foods&quot;</code></pre>
<p>It would be interesting to compare fast foods and restaurant foods. But that would mean running two PCAs <em>and ain’t nobody got time for that</em>… so let’s look at baby food!</p>
</div>
<div id="clean-the-data" class="section level4">
<h4>Clean the data</h4>
<pre class="r"><code>food_subset &lt;- food %&gt;% 
  clean_names() %&gt;%
  mutate(food_group = str_to_lower(food_group)) %&gt;%
  filter(food_group == &quot;baby foods&quot;) %&gt;% #only look at baby food
  select(energy_kcal:zinc_mg) #choose variables to keep</code></pre>
</div>
<div id="run-the-pca" class="section level4">
<h4>Run the PCA</h4>
<pre class="r"><code>food_pca &lt;- prcomp(food_subset, scale=TRUE)

#Is there missingness?
naniar::gg_miss_var(food_subset) #nope!</code></pre>
<p><img src="/post/external-project/index_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>#Proportion of variance &amp; cumulative variance explained by each PC
summary(food_pca)</code></pre>
<pre><code>## Importance of components:
##                           PC1    PC2    PC3     PC4     PC5     PC6     PC7
## Standard deviation     3.5678 1.9864 1.0072 0.96507 0.94867 0.81465 0.70345
## Proportion of Variance 0.5535 0.1716 0.0441 0.04049 0.03913 0.02885 0.02152
## Cumulative Proportion  0.5535 0.7250 0.7691 0.80961 0.84874 0.87760 0.89911
##                            PC8     PC9    PC10    PC11    PC12    PC13    PC14
## Standard deviation     0.65706 0.57426 0.49328 0.46338 0.42703 0.41429 0.36897
## Proportion of Variance 0.01877 0.01434 0.01058 0.00934 0.00793 0.00746 0.00592
## Cumulative Proportion  0.91788 0.93222 0.94280 0.95213 0.96006 0.96753 0.97344
##                           PC15    PC16    PC17    PC18    PC19    PC20    PC21
## Standard deviation     0.36158 0.35354 0.32335 0.29762 0.25092 0.20141 0.18732
## Proportion of Variance 0.00568 0.00543 0.00455 0.00385 0.00274 0.00176 0.00153
## Cumulative Proportion  0.97913 0.98456 0.98911 0.99296 0.99570 0.99746 0.99899
##                          PC22    PC23
## Standard deviation     0.1517 0.01721
## Proportion of Variance 0.0010 0.00001
## Cumulative Proportion  1.0000 1.00000</code></pre>
<pre class="r"><code>#Visualize scree plot
plot(food_pca)</code></pre>
<p><img src="/post/external-project/index_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre class="r"><code># The amount of variation explained drops off dramatically after PC1, but even moreso after PC2. 

#Rotations (linear combinations for each PC):
food_rotation &lt;- food_pca</code></pre>
<p>Dang, PC1 explains 55.3% of variance, and PC2 explains 17.2% of variance - that’s a lot of variance explained with just the first two principal components given we have 23 PCs to work with!</p>
</div>
<div id="plot-the-biplot" class="section level4">
<h4>Plot the biplot</h4>
<pre class="r"><code>autoplot(food_pca,
         colour = &quot;grey80&quot;,
         loadings.label = TRUE,
         loadings.label.size = c(3,4,3,4,4,4,4,3,3,4,4,4,4,4,3,3,4,3,3,3,4,3,3),
         loadings.label.hjust = c(1,1,1,3,2,1.5,1,1,2,1,2,2,1,1.5,1,1,1.5,2,0.5,1,1,1,1),
         loadings.label.colour = &quot;black&quot;,
         loadings.label.repel = TRUE,
         alpha = 0.5) +
  theme_bw() +
  scale_x_continuous(limits = c(-0.2, 0.05)) +
  scale_y_continuous(limits = c(-0.3, 0.2))</code></pre>
<p><img src="/post/external-project/index_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Figure 1. Principal components analysis (PCA) on food nutrients measured in baby food sold in the United States. Principal component 1 (PC1) accounted for 55.35% of variation in food nutrients, and principal component 2 (PC2) accounted for an additional 17.16% of food nutrient variation.</p>
</div>
<div id="so-what-does-this-mean" class="section level4">
<h4>So, what does this mean?</h4>
<p>In baby food, highly positively correlated nutrient pairs are: riboflavin and niacin, carbohydrates and phosphorus, copper and protein, vitamin E and folate, and sugar and vitamin B12. Fiber is minimally correlated with vitamin A, vitamin C, and manganese.</p>
<p>Additional research is needed to understand why vitamin B12 and sugar are so highly correlated in baby food…
<img src="babyfood.jpg" /></p>
</div>
